--- # set up account for brian
- hosts:
  - debian
  become: yes

  vars:
    username: brian
    githubname: brianbauer42
    prereqs:
      - zsh
      - git
      - acl
      - gnupg
      - vim
      - curl

  # TODO: Set account password in vault? https://stackoverflow.com/questions/19292899/creating-a-new-user-and-password-with-ansible

  pre_tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: Install useful packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items: "{{ prereqs }}"

  - name: Create user w/ default shell ZSH
    user:
      name: "{{ username }}"
      shell: /bin/zsh
      state: present

  - name: Creates .ssh directory
    file:
      path: "/home/{{ username }}/.ssh"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0600

  - name: Download SSH keys from github
    ansible.builtin.get_url:
      url: "https://github.com/{{ githubname }}.keys"
      dest: "/home/{{ username }}/.ssh/authorized_keys"

  - name: set permissons for authorized keys
    ansible.builtin.file:
      path: "/home/{{ username }}/.ssh/authorized_keys"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '644'

  - name: set permissons for .ssh directory
    ansible.builtin.file:
      path: "/home/{{ username }}/.ssh"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '700'

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) ALL'
      validate: visudo -cf %s
    environment: 
      PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"

  - name: Add user to wheel group
    user:
      name: "{{ username }}"
      groups: wheel
      append: yes

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ username }}"
          oh_my_zsh:
            theme: homelab-server
            plugins:
              - git
              - colorize
              - jsontools
            update_mode: reminder
            update_frequency: 3

  post_tasks:
    - name: Download custom prompt for oh-my-zsh
      get_url:
        url: "https://raw.githubusercontent.com/brianbauer42/homelab-ansible/main/config-files/homelab-server.zsh-theme"
        dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/homelab-server.zsh-theme"
