---
- hosts: localhost
  vars_prompt:
    - name: target_host
      prompt: please enter the target host IP. comma separated list acceptable.
      private: no

  tasks:
    - name: Parse hosts list
      add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      loop: "{{ target_host.split(',') }}"

- hosts:
  - dynamically_created_hosts

  vars_prompt:  
    - name: username
      prompt: Enter username to change the password for
      private: false

    - name: new_password
      prompt: What is the new password?
      private: true
  
  tasks:
    - name: "Change {{ usernames }}'s password"
      become: true
      user:
        name: "{{ username }}"
        update_password: always
        password: "{{ new_password | password_hash('sha512') }}"